apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kinto-objects.codeformuenster.org
spec:
  group: codeformuenster.org
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: kinto-objects
    singular: kinto-object
    kind: KintoObject
    shortNames:
      - ko
  # preserveUnknownFields: false
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            server:
              type: string
            authSecret:
              type: object
              properties:
                name:
                  type: string
            objects:
              type: object
              properties:
                configMap:
                  type: object
                  properties:
                    name:
                      type: string
